import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Mitr } from 'next/font/google';
import "./styles/globals.css";
import TopBar from "./components/TopBar";

const mitr = Mitr({
  weight: ['200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`h-full w-full ${mitr.className}`}>{children}
        <TopBar/>
      </body>
    </html>
  );
}
